[package]
name = "A346507"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
rayon = "1.5.1"


[profile.release-checked]
inherits = "release"
overflow-checks = true
lto = true
